### ISSUE TITLE
issue with file

### ISSUE THREAD

**Issue by obar1** [mashu3/epub2pdf#1]
```
epub2pdf 9781098108298.epub
Traceback (most recent call last):
  File "/home/xsazcd/git/obar1/0to100.oreilly.git/.venv/bin/epub2pdf", line 33, in <module>
    sys.exit(load_entry_point('epub2pdf==0.1.0', 'console_scripts', 'epub2pdf')())
  File "/home/xsazcd/git/obar1/0to100.oreilly.git/.venv/lib/python3.10/site-packages/epub2pdf.py", line 258, in main
    converter.convert()
  File "/home/xsazcd/git/obar1/0to100.oreilly.git/.venv/lib/python3.10/site-packages/epub2pdf.py", line 156, in convert
    page_index = self.extract_epub_index(epub, page_names, ncx_name)
  File "/home/xsazcd/git/obar1/0to100.oreilly.git/.venv/lib/python3.10/site-packages/epub2pdf.py", line 107, in extract_epub_index
    index_number = page_names.index(nav_text)
ValueError: 'OEBPS/preface01.xhtml#preface_idQ8pGjx' is not in list
```

**Comment by obar1** [comment]
I cannot shar the file unfortunately
